<img src="https://electronaut.info/wp-content/uploads/2017/05/Tubescape_jupyter2.jpg">

<h1><font color = b30000>TUBE DATA MATCHER for uTRACER FILES</font></h1><h5>Anode current for a sweep of grid voltages  when anode voltage = constant</h5>

# STEP 1 — Import and process tube data, build dataframe.

In [1]:
from electronaut_uTracer_Import import *
df.head()

Please enter the path to the folder containing the uTracer files: /Users/rrmc/Desktop/5749_197_onward_2

What type of tubes are these? 5749

— — — — —

Data from 211 tubes of type 5749 was successfully read.
A dataframe containing all 211 tubes was successfully created.

,tube_ID,tube_type,anode_voltage,Bias_2,Bias_6,Bias_10,Bias_14,Bias_18,Bias_22,Bias_26,Bias_30,Bias_34,Bias_38,Bias_42,Bias_46,Bias_50
0,198,5749,325,95.683,61.076,41.02,30.853,24.037,18.882,14.949,11.944,9.677,7.98,6.698,5.718,5.018
1,201,5749,325,61.619,38.735,25.431,19.238,14.687,11.189,8.626,6.769,5.411,4.438,3.757,3.28,2.933
2,202,5749,325,85.154,55.701,37.093,27.605,21.273,16.593,13.053,10.365,8.332,6.782,5.616,4.73,4.117
3,203,5749,325,76.811,49.356,32.624,23.867,17.923,13.45,10.091,7.651,5.928,4.754,3.962,3.346,2.848
4,205,5749,325,69.774,45.639,30.419,22.742,17.214,13.077,9.996,7.71,6.074,4.911,4.092,3.495,3.045

In [ ]:
# NOT WORKING YET

from bokeh.plotting import figure, output_file, show

output_file("TubeDataSet_Range.html")

p = figure(plot_width=800, plot_height=600)
p.outline_line_width = 5
p.outline_line_alpha = 0.5
p.outline_line_color = "red"

# Make a list for the x_values by chopping off all the "bias_" column name prefixes and converting to ints
x_values = [int(i[5:]) for i in temp_columns if i.startswith('Bias_') == True]        

all_x_values, all_y_values, total = [], [], []

# for i in list(df.index[0:5]):
#     y_values = list((df.iloc[(int(temp_tube))]))[3:]
    
#     all_x_values.append(x_values)
#     all_y_values.append(y_values)
  
all_x_values = [[3,2,1],[3,5,6]]    
all_y_values = [[9,8,7],[6,5,4]]    


print("X", all_x_values)
print("Y", all_y_values)

      
      
p.multi_line(all_x_values, all_y_values,
                 color=["firebrick", "navy"], alpha=[0.8, 0.3], line_width=1)
    
    
    
# p.line(all_x_values, all_y_values, line_width=1)    
    

show(p)

##### TODO:  INSERT PLOT OF ALL TUBES


# STEP 3: Show the statistics of the tube data set

In [2]:
# For some reason, .describe is requiring the .astype(float) in order to show the stats.
df_stats = df.astype(float).describe()
df_stats.loc[:, 'tube_type'] = df_stats.loc[:, 'tube_type'].astype(int)
df_stats.loc[:, 'tube_ID'] = df_stats.loc[:, 'tube_ID'].astype(int)
# df_stats.loc[:, 'tube_ID'] = df_stats.loc[:, 'tube_ID'].astype(str)
df_stats

,tube_ID,tube_type,anode_voltage,Bias_2,Bias_6,Bias_10,Bias_14,Bias_18,Bias_22,Bias_26,Bias_30,Bias_34,Bias_38,Bias_42,Bias_46,Bias_50
count,211,211,211.0,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000
mean,328,5749,325.0,79.952791,51.636057,34.172389,25.309730,19.268626,14.793450,11.480981,9.025626,7.227834,5.936280,4.998265,4.285355,3.732882
std,75,0,0.0,10.661666,6.825628,4.753049,3.578094,2.831172,2.301914,1.908458,1.601711,1.353946,1.152915,0.991275,0.864486,0.764835
min,198,5749,325.0,28.079000,12.105000,4.034000,2.148000,1.499000,1.111000,0.832000,0.622000,0.474000,0.374000,0.300000,0.251000,0.218000
25%,261,5749,325.0,73.903500,47.955000,31.725000,23.520000,17.773000,13.512500,10.348000,8.046500,6.364000,5.203000,4.399500,3.770500,3.315500
50%,329,5749,325.0,80.016000,51.886000,34.401000,25.512000,19.391000,14.928000,11.544000,9.060000,7.222000,5.941000,5.034000,4.320000,3.757000
75%,393,5749,325.0,87.892000,56.481000,37.476500,27.811500,21.246000,16.442500,12.854500,10.172000,8.169000,6.727500,5.624500,4.820500,4.198500
max,456,5749,325.0,101.499000,66.349000,44.818000,33.614000,26.418000,20.968000,16.726000,13.975000,12.071000,10.576000,9.385000,8.366000,7.508000

In [ ]:
# This is ugly still.  Work in progress.

from bokeh.plotting import figure, output_file, show

output_file("Tube_Batch_Statistics.html")

p = figure(plot_width=800, plot_height=600)

temp_columns = list(df_stats.columns)
stats_columns = []

# Make a list for the x_values by chopping off all the "bias_" column name prefixes and converting to ints
x_values = [int(i[5:]) for i in temp_columns if i.startswith('Bias_') == True]        

# Make a list of the min values and plot
y_min = list(df_stats.loc['min'])
y_min = y_min[3:]
p.line(x_values, y_min, line_width=2)

# Make a list of the max values and plot
y_max = list(df_stats.loc['max'])
y_max = y_max[3:]
p.line(x_values, y_max, line_width=2)

# Make a list of the mean values and plot
y_mean = list(df_stats.loc['mean'])
y_mean = y_mean[3:]
p.line(x_values, y_mean, line_width=2)
show(p)

In [ ]:
# Also ugly

p.multi_line([x_values, x_values, x_values], [y_min, y_max, y_mean],
             color=["firebrick", "navy"], alpha=[0.8, 0.3, 0.5], line_width=4)

show(p)

##### TODO:  INSERT PLOT(S) OF STATISTICS

# STEP 4: Calculate the differences between all tubes

In [3]:
from ipywidgets import FloatProgress
from IPython.display import display
import time

start_time = time.time() 

def build_difference_df(df, df_stats):
    
    # Display a progress bar
    build_diff_progress_bar = FloatProgress(min=0, max=100)
    display(build_diff_progress_bar)
       
    # Make a list of all the columns in the dataframe
    cols = list(df.columns)
    
    # Make a list of just the bias columns
    bias_list = []
    for i in cols:
        if i.startswith('Bias_') == True:
            bias_list.append(i)
    
    # BMake an empty list to hold the calculated values, to be used to build the difference dataframe
    diff_squared_list = []
    
    # Iterate through the index of tubes in the master dataframe to select a reference tube
    for each_ref_tube in df.index:
        
        # Get the next reference tube data, as a series
        ref_tube = df.iloc[each_ref_tube]
        ref_tube_ID = ref_tube.tube_ID

        # Iterate through the index of tubes in the master dataframe to select a match tube
        for each_match_tube in df.index:
            
            # Get the next tube data to be compared, as a series
            match_tube = df.iloc[each_match_tube]
            match_tube_ID = match_tube.tube_ID
            
            # Dictionary container to hold the difference variables for each tube
            temp_dict = {}
            
            # Compute the squares of the differences in each current measurement
            error_sum = 0
            for bias in enumerate(bias_list):
                mismatch = ((float(match_tube.loc[bias[1]]) - float(ref_tube.loc[bias[1]]))**2)
                temp_dict[bias[1]] = mismatch
                error_sum = error_sum + mismatch

            # Add other relevant key/value pairs to the dictionary  
            temp_dict['ref_tube_ID'] = ref_tube_ID
            temp_dict['match_tube_ID'] = match_tube_ID
            temp_dict['error_sum'] = error_sum

            # Append the tube's calculated values to the diff_squared_list
            diff_squared_list.append(temp_dict)
            
            # Update the progress bar
            build_diff_progress_bar.value += 1

    
    # Make an ordered list for the columns of the new difference dataframe
    new_cols_to_add = ['ref_tube_ID', 'match_tube_ID', 'error_sum']
    df_dif_cols = new_cols_to_add + bias_list
    df_dif = pd.DataFrame(diff_squared_list, columns = df_dif_cols)

    return df_dif
    
    
df_dif = build_difference_df(df, df_stats)

# Produce a brief report:
total_rows = len(df_dif)
total_columns = len(df_dif.columns)
total_datapoints = total_rows * total_columns
stop_time = time.time()
elapsed_time = stop_time - start_time
print("It took", round(elapsed_time, 2), "seconds to calculate", 
      total_datapoints, "values, resulting in", len(df_dif), "rows.")

# Display the head of the difference dataframe
df_dif.head()

It took 33.46 seconds to calculate 712336 values, resulting in 44521 rows.

,ref_tube_ID,match_tube_ID,error_sum,Bias_2,Bias_6,Bias_10,Bias_14,Bias_18,Bias_22,Bias_26,Bias_30,Bias_34,Bias_38,Bias_42,Bias_46,Bias_50
0,198,198,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,198,201,2300.452296,1160.356096,499.120281,243.016921,134.908225,87.422500,59.182249,39.980329,26.780625,18.198756,12.545764,8.649481,5.943844,4.347225
2,198,202,190.891471,110.859841,28.890625,15.421329,10.549504,7.639696,5.239521,3.594816,2.493241,1.809025,1.435204,1.170724,0.976144,0.811801
3,198,203,764.008486,356.152384,137.358400,70.492816,48.804196,37.380996,29.506624,23.600164,18.429849,14.055001,10.407076,7.485696,5.626384,4.708900
4,198,205,1248.483155,671.276281,238.300969,112.381201,65.788321,46.553329,33.698025,24.532209,17.926756,12.981609,9.418761,6.791236,4.941729,3.892729

In [5]:
len(df_dif)

44521

# Find the best matches for a particular tube_ID

In [6]:
# This function requires the tube_to_match and tube_set_size variable to be set manually, below.

def find_best_set_for_chosen_tube_ID(tube_to_match, tube_set_size):
    tube_to_match = str(tube_to_match)
    
    # Create a new dataframe showing only tube_set_size number of nearest matches to the chosen tube_to_match
    df_tube_set = df_dif[(df_dif.ref_tube_ID == tube_to_match)].sort_values('error_sum').head(tube_set_size)
    
    return df_tube_set

tube_to_match = 419
tube_set_size = 2
df_tube_set = find_best_set_for_chosen_tube_ID(tube_to_match, tube_set_size)
df_tube_set.head(tube_set_size)

,ref_tube_ID,match_tube_ID,error_sum,Bias_2,Bias_6,Bias_10,Bias_14,Bias_18,Bias_22,Bias_26,Bias_30,Bias_34,Bias_38,Bias_42,Bias_46,Bias_50
37736,419,419,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37715,419,392,1.600525,0.225625,0.935089,0.073984,0.058081,0.066049,0.021316,0.0049,0.000289,0.011025,0.034969,0.054756,0.062001,0.052441

In [ ]:
df_tube_set

In [ ]:
# Total up the error_sum column to create a score for the tube set.  Lower is better. 
tube_set_score = df_tube_set.error_sum.sum()
print("Tube-set SCORE:", tube_set_score, " (Lower is better)")

# STEP 5:  Build a dataframe of the best matched sets in order

In [ ]:
# math lib used for generating ordinal strings; i.e. ['1st', '2nd', '3rd'] etc.
import math


# Make a local version of df_dif that can be butchered
df_dif_copy = df_dif.copy()

def ask_tube_set_size():
    
    # Ask the user to enter the set size
    tube_set_size = input("Please enter the number of tubes per matched set:")
    
    # Build a list of tube names for the tube set size
    tube_sets_columns = ['Tube_' + str(1 + i) for i in range(int(tube_set_size))]    
    
    return tube_set_size, tube_sets_columns 


def find_best_set_for_chosen_tube_ID(df_dif_copy, tube_to_match, tube_set_size, tube_sets_columns):
    tube_to_match = str(tube_to_match)
        
    # Create a new dataframe showing only tube_set_size number of nearest matches to the chosen tube_to_match
    df_tube_set = df_dif_copy[(df_dif_copy.ref_tube_ID == tube_to_match)].sort_values('error_sum').head(int(tube_set_size))
        
    # Create the dictionary of the tubes in the set and the total score of the set
    tube_set_list = list(df_tube_set.match_tube_ID)
    tube_set_dict = dict(zip(tube_sets_columns, tube_set_list))   
    tube_set_score = df_tube_set.error_sum.sum()
    tube_set_dict.update({'tube_set_score':tube_set_score})

    return tube_set_dict


def find_best_set(df_dif_copy, tube_set_size, tube_sets_columns):
    
    # Make an empty list to hold the tube sets and their scores
    tube_sets_and_scores_list = []
    temp_dict = {}
    
    if 'tube_set_score' in tube_sets_columns:
        tube_sets_columns.remove('tube_set_score')

    for i in df_dif_copy.ref_tube_ID.unique():
        temp_dict = find_best_set_for_chosen_tube_ID(df_dif_copy, i, tube_set_size, tube_sets_columns)
        tube_sets_and_scores_list.append(temp_dict)

    # Add 'tube_set_score' column name at the front of the list
    if 'tube_set_score' not in tube_sets_columns: 
        tube_sets_columns.insert(0, 'tube_set_score')    
    
    # Create a dataframe for the tube sets called df_tube_sets 
    df_tube_sets = pd.DataFrame(tube_sets_and_scores_list, columns=tube_sets_columns)
    
    # Sort the tube_set_score column, take the top row (with the lowest score) as a new df 
    df_best_set_temp = df_tube_sets.sort_values('tube_set_score').head(1)
        
    return df_best_set_temp
 
    
# Start a timer
start_time = time.time()   
    
# Make an empty dataframe to hold all the sets and their scores
df_best_tube_sets = pd.DataFrame()

# Get the tube_set_size and the tube_sets_columns from the ask_tube_set_size function
tube_set_size, tube_sets_columns = ask_tube_set_size()

# Get the best tube set from the batch
df_best_set_temp = find_best_set(df_dif_copy, tube_set_size, tube_sets_columns) 

# Display a progress bar
progress_bar_range = int(len(df)/int(tube_set_size))
best_matched_progress_bar = FloatProgress(min=0, max=progress_bar_range)
display(best_matched_progress_bar)

# Append the best tube set to the df_best_tube_sets dataframe
df_best_tube_sets = df_best_tube_sets.append(df_best_set_temp)

# Remove the best tube set from df_dif_copy
tube_delete_list = list(df_best_set_temp.iloc[0])
tube_delete_list.pop(0)
df_dif_copy = df_dif_copy[~df_dif_copy.ref_tube_ID.isin(tube_delete_list)]
df_dif_copy = df_dif_copy[~df_dif_copy.match_tube_ID.isin(tube_delete_list)]

# A function to generate ordinal strings; i.e. ['1st', '2nd', '3rd'] etc.
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(math.floor(n/10)%10!=1)*(n%10<4)*n%10::4])
ordinal_list = [ordinal(n) for n in range(1, int(len(df)))]

set_count = 1
print()
print("*** BEST! ***")
print(ordinal_list[0],"best tube set SCORE:", str(df_best_set_temp.tube_set_score.iloc[0]))
print("TUBES:", tube_delete_list)

# Update the progress bar
best_matched_progress_bar.value += 1


while len(df_dif_copy.ref_tube_ID.unique()) >= int(tube_set_size):
    # Get all the rest of the sets from the batch
    df_best_set_temp = find_best_set(df_dif_copy, tube_set_size, tube_sets_columns)
    
    # Append the best tube set to the df_best_tube_sets dataframe
    df_best_tube_sets = df_best_tube_sets.append(df_best_set_temp)

    # Remove the best tube set from df_dif_copy
    tube_delete_list = list(df_best_set_temp.iloc[0])
    tube_delete_list.pop(0)

    df_dif_copy = df_dif_copy[~df_dif_copy.ref_tube_ID.isin(tube_delete_list)]
    df_dif_copy = df_dif_copy[~df_dif_copy.match_tube_ID.isin(tube_delete_list)]
    print()
    print(ordinal_list[set_count],"best tube set SCORE:", str(df_best_set_temp.tube_set_score.iloc[0]))
    print("TUBES:", tube_delete_list)

    set_count += 1
    
    # Update the progress bar
    best_matched_progress_bar.value += 1


stop_time = time.time()
elapsed_time = stop_time - start_time
print()
print("It took", round(elapsed_time, 2), "seconds to produce", set_count, "tube sets.")

In [ ]:
# Display the tube sets as a dataframe
df_best_tube_sets.sort_values('tube_set_score').head(15)

### Everything below this line is experimental

In [ ]:
df_best_tube_sets.tube_set_score[:15].describe()

In [ ]:
import seaborn as sns
sns.set()

df_sns = df_best_tube_sets[['tube_set_score']][:15].copy()

sns.pairplot(df_sns, 'tube_set_score')
sns.plt.show()

In [ ]:
from bokeh.charts import Histogram, output_file, show

p = Histogram(df_best_tube_sets['tube_set_score'], title="Tube Set Scores")

output_file("histogram.html",)

show(p)

# Miscellaneous exeriments with ipywidgets

In [ ]:
import ipywidgets as wg
from ipywidgets import Layout, Box
from IPython.display import display


# Make a list of all the tube_ID names, then build a select box with those values
tube_list = list(df.loc[:, 'tube_ID'])
tube_list.sort(key=int)
tube_ID_select_box = wg.Select(options=tube_list, value=tube_list[0], description='Reference Tube', layout=Layout(width='150px'), disabled=False)

# Make a list of the tubes for the "Matched Tubes" selectMultiple box
matched_list = ['1', '33', '67', '22', '45']
matched_tube_box = wg.SelectMultiple(options=matched_list, layout=Layout(display="flex", flex_flow='column', width='350px'), description="Matched Tubes") 


items = [tube_ID_select_box, matched_tube_box]

box_layout = Layout(display='flex',
                    flex_flow='row',
                    align_items='stretch',
                    border='solid',
                    width='100%')
box = Box(children=items, layout=box_layout)

box


# def respond(sender):
    # pass the chosen Tube_ID to a function that looks up the resulting match list, then fill the match list box
    
    
# display(tube_ID_select_box,matched_tube_box)
# tube_ID_select_box.observe(respond)

# Other Miscellaneous stuff

##### Apply a function to a column
df.Bias_2.max()

In [ ]:
% lsmagic

In [ ]:
%pprint

In [ ]:
# Applymap is useful for applying a function to all data
# For example, converting all data from floats to ints
# df.loc[2:7, 'Bias_2': 'Bias_50'].applymap(int)

In [ ]:
# List all available magics
% lsmagic

In [ ]:
# Display environmental variables
env_variables = %env
current_path = env_variables.get('PATH')
current_path

In [ ]:
mydict = % env
mydict.keys()

In [ ]:
% env

In [ ]:
# % time x = range(10000)
% timeit x = range(10000)
max(x)